# Generated by Django 5.0 on 2024-01-30 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0004_alter_inventory_adjustment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_adjustment_history',
            name='Action',
            field=models.CharField(choices=[('created', 'Created'), ('edited', 'Edited')], max_length=255, null=True),
        ),
    ]
