# Generated by Django 5.0 on 2024-01-30 18:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0005_alter_inventory_adjustment_history_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory_adjustment_history',
            name='Date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
