# Generated by Django 5.0 on 2024-01-31 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0007_inventory_adjustment_history_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory_adjustment_history',
            name='item',
        ),
    ]
