# Generated by Django 5.0 on 2024-03-14 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Company_Staff', '0010_inventory_adjustment_items_comment'),
        ('Company_Staff', '0020_auto_20240309_0616'),
    ]

    operations = [
    ]
